version: '3.3'
services:
  vfb-kb:
    image: virtualflybrain/docker-neo4j-knowledgebase:neo2owl
    environment:
      - NEO4J_AUTH=neo4j/neo
      - NEO4J_dbms_read__only=false
      - NEO4J_dbms_memory_heap_maxSize=6G
      - NEO4J_dbms_memory_heap_initial__size=1G 
    ports:
      - 7474:7474
      - 7687:7687
  vfb-data-ingest-api:
    image: matentzn/vfb-data-ingest-api:latest
    depends_on:
      - vfb-kb
    links:
      - vfb-kb
    ports:
      - 5000:5000
    environment:
      - KBserver=http://vfb-kb:7474
      - KBuser=neo4j
      - KBpassword=neo
  vfb-data-ingest-ui:
    image: matentzn/vfb-data-ingest-ui:latest
    depends_on:
      - vfb-data-ingest-api
    links:
      - vfb-data-ingest-api
    ports:
      - 8080:8080
    environment:
      - CURATIONAPI=http://vfb-data-ingest-api:5000/api
